# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-11 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddr', models.CharField(max_length=16, unique=True, verbose_name='\u4e3b\u673aIP\u5730\u5740')),
                ('hostname', models.CharField(max_length=50, null=True, verbose_name='\u4e3b\u673a\u540d\u79f0')),
                ('username', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u7528\u6237\u540d\u79f0')),
                ('password', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u7528\u6237\u5bc6\u7801')),
                ('sshport', models.IntegerField(blank=True, default=22, verbose_name='SSH\u7aef\u53e3\u53f7')),
                ('remark', models.CharField(max_length=255, null=True, verbose_name='\u8bf4\u660e')),
            ],
        ),
    ]
