# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-11 06:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websys', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HostManager',
            new_name='opp_host',
        ),
    ]
