# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50, unique=True, verbose_name='\u9879\u76ee\u540d\u79f0')),
                ('img_version', models.IntegerField(verbose_name='docker\u6700\u540e\u955c\u50cf\u7248\u672c')),
                ('container_flag', models.IntegerField(verbose_name='\u524d\u4e00\u4e2a\u5bb9\u5668\u5e8f\u53f7')),
                ('project_type', models.CharField(choices=[(b'PHP', b'php'), (b'TOMCAT', b'tomcat')], default=b'php', max_length=100, null=True, verbose_name='\u9879\u76ee\u7c7b\u578b')),
                ('default_port', models.IntegerField(choices=[(b'8080', b'8080'), (b'80', b'80')], default=b'80', null=True, verbose_name='\u9ed8\u8ba4\u7aef\u53e3')),
                ('balance_vip', models.CharField(max_length=200, null=True, verbose_name='\u8d1f\u8f7d\u5747\u8861IP\u96c6')),
                ('cluster_ip', models.TextField(null=True, verbose_name='\u96c6\u7fa4\u8282\u70b9IP\u96c6')),
            ],
        ),
    ]
