# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compose',
            name='container_flag',
            field=models.IntegerField(choices=[(b'1', 1), (b'2', 2)], verbose_name='\u524d\u4e00\u4e2a\u5bb9\u5668\u5e8f\u53f7'),
        ),
    ]
