# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0003_auto_20160506_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80, verbose_name='\u7528\u6237\u540d\u79f0')),
                ('password', models.CharField(max_length=20, verbose_name='\u7528\u6237\u5bc6\u7801')),
                ('host_ip', models.CharField(max_length=20, unique=True, verbose_name='\u4e3b\u673aIP')),
                ('host_name', models.CharField(max_length=50, null=True, verbose_name='\u4e3b\u673a\u540d\u79f0')),
                ('ssh_port', models.IntegerField(default=22, verbose_name='SSH\u7aef\u53e3\u53f7')),
                ('docker_port', models.IntegerField(blank=True, default=5555, null=True, verbose_name='docker\u7aef\u53e3\u53f7')),
                ('remark', models.CharField(max_length=100, null=True, verbose_name='\u8bf4\u660e')),
            ],
        ),
        migrations.AddField(
            model_name='compose',
            name='store_img_host',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u5b58\u50a8\u955c\u50cf\u7684\u4e3b\u673a'),
        ),
        migrations.AlterField(
            model_name='compose',
            name='default_port',
            field=models.IntegerField(choices=[(8080, 8080), (80, 80)], default=80, null=True, verbose_name='\u670d\u52a1\u9ed8\u8ba4\u7aef\u53e3'),
        ),
    ]
