# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0004_auto_20160511_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compose',
            name='store_img_host',
            field=models.CharField(max_length=20, verbose_name='\u5b58\u50a8\u955c\u50cf\u7684\u4e3b\u673a'),
        ),
    ]
