# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0005_auto_20160511_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='compose',
            name='img_ver2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u955c\u50cf\u7248\u672c2'),
        ),
        migrations.AddField(
            model_name='compose',
            name='nat_port',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u8f6c\u53d1\u7aef\u53e3'),
        ),
        migrations.AlterField(
            model_name='hostmanager',
            name='docker_port',
            field=models.IntegerField(default=5555, verbose_name='docker\u7aef\u53e3\u53f7'),
        ),
    ]
