# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-08 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0007_auto_20160627_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50, verbose_name='\u9879\u76ee\u540d\u79f0')),
                ('project_env', models.CharField(choices=[(b'PROD', b'prod'), (b'STAGING', b'staging')], default=b'staging', max_length=20, verbose_name='\u9879\u76ee\u73af\u5883')),
                ('db_version', models.CharField(max_length=100, verbose_name='\u6570\u636e\u5e93\u7248\u672c')),
                ('db_host', models.CharField(max_length=30, verbose_name='\u8fde\u63a5\u6570\u636e\u5e93\u4e3b\u673a\u5730\u5740')),
                ('db_name', models.CharField(max_length=20, verbose_name='\u6570\u636e\u5e93\u540d\u79f0')),
                ('db_user', models.CharField(max_length=20, verbose_name='\u8fde\u63a5\u6570\u636e\u5e93\u7528\u6237\u540d')),
                ('db_passwd', models.CharField(max_length=30, verbose_name='\u8fde\u63a5\u6570\u636e\u5e93\u5bc6\u7801')),
            ],
        ),
    ]
