# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-08 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0008_dbmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbmanager',
            name='db_host',
            field=models.CharField(max_length=100, verbose_name='\u8fde\u63a5\u6570\u636e\u5e93\u4e3b\u673a\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='dbmanager',
            name='db_passwd',
            field=models.CharField(max_length=50, verbose_name='\u8fde\u63a5\u6570\u636e\u5e93\u5bc6\u7801'),
        ),
        migrations.AlterField(
            model_name='dbmanager',
            name='db_version',
            field=models.CharField(max_length=30, verbose_name='\u6570\u636e\u5e93\u7248\u672c'),
        ),
        migrations.AlterField(
            model_name='dbmanager',
            name='project_name',
            field=models.CharField(max_length=20, verbose_name='\u9879\u76ee\u540d\u79f0'),
        ),
    ]
